// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJ2ucW5P64R5abjX1hDHntrt1yrcuiWA',
    appId: '1:641989378581:web:65c391901f10d23f5cc41c',
    messagingSenderId: '641989378581',
    projectId: 'personals-36861',
    authDomain: 'personals-36861.firebaseapp.com',
    storageBucket: 'personals-36861.firebasestorage.app',
    measurementId: 'G-V0446K1HEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngpVI0x58oldCDYuGdeuRb3zSOvQ_goM',
    appId: '1:641989378581:android:5f94085adce29b505cc41c',
    messagingSenderId: '641989378581',
    projectId: 'personals-36861',
    storageBucket: 'personals-36861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbK955otXDzXLqSlr9eXxWgyw_gZ9mWL8',
    appId: '1:641989378581:ios:a354a938bcd957335cc41c',
    messagingSenderId: '641989378581',
    projectId: 'personals-36861',
    storageBucket: 'personals-36861.firebasestorage.app',
    iosClientId: '641989378581-vplh0t7m542ltl26afv9lt9i25lt4hu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbK955otXDzXLqSlr9eXxWgyw_gZ9mWL8',
    appId: '1:641989378581:ios:a354a938bcd957335cc41c',
    messagingSenderId: '641989378581',
    projectId: 'personals-36861',
    storageBucket: 'personals-36861.firebasestorage.app',
    iosClientId: '641989378581-vplh0t7m542ltl26afv9lt9i25lt4hu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJ2ucW5P64R5abjX1hDHntrt1yrcuiWA',
    appId: '1:641989378581:web:1d2bfb0628aedc485cc41c',
    messagingSenderId: '641989378581',
    projectId: 'personals-36861',
    authDomain: 'personals-36861.firebaseapp.com',
    storageBucket: 'personals-36861.firebasestorage.app',
    measurementId: 'G-1RML1EJ2G9',
  );
}
